import logo from "./logo2.png"
import "./terms.css"
export default function Terms(){
    return (
        <div className="terms">
            <div>
                <img alt="" src={logo}/>
                <h2>#TEAM ARM</h2>
            </div>
            <div className="terms-container">
                <h4>TERMS OF USE</h4>
                <p>IMPORTANT – THIS IS A LEGAL AGREEMENT BETWEEN YOU AND MR.BEASTYOUTUBE, LLC (“MR.BEAST” OR “WE” OR “US” OR “OUR”). THE WEBSITE LOCATED AT WWW.TEAMSEAS.ORG (THE "WEBSITE"), IS OWNED AND OPERATED BY MR. BEAST. BEFORE ACCESSING OR USING ANY PART OF THE WEBSITE, YOU SHOULD READ CAREFULLY THE FOLLOWING TERMS AND CONDITIONS CONTAINED IN THIS TERMS OF USE AGREEMENT. YOUR ACCESS TO AND USE OF THE WEBSITE ARE SUBJECT TO THESE TERMS OF USE, AS WELL AS TO ALL APPLICABLE LAWS AND REGULATIONS, AND ALONG WITH ANY OTHER TERMS AND CONDITIONS AS MAY BE SET FORTH BY MR.BEAST.</p>
                <p>MR.BEAST IS WILLING TO LICENSE AND ALLOW THE USE OF THIS WEBSITE ONLY ON THE CONDITION THAT YOU ACCEPT AND AGREE TO ALL OF THE TERMS AND CONDITIONS CONTAINED IN THESE TERMS OF USE. IF YOU DO NOT AGREE WITH THESE TERMS OF USE, YOU ARE NOT GRANTED PERMISSION TO ACCESS OR OTHERWISE USE THE WEBSITE. YOUR ACCESS TO AND USE OF THIS WEBSITE CONSTITUTES YOUR ACCEPTANCE OF AND AGREEMENT TO ABIDE BY THESE TERMS OF USE. THESE TERMS OF USE MAY BE MODIFIED BY MR.BEAST FROM TIME TO TIME WITHOUT ADVANCE NOTICE BY POSTING HERE AND YOU WILL BE BOUND BY ANY SUCH MODIFIED TERMS OF USE IF YOU CONTINUE TO USE THIS WEBSITE AFTER SUCH CHANGES ARE POSTED. THE DATE THESE TERMS OF USE WERE LAST UPDATED IS STATED AT THE END OF THIS DOCUMENT. YOU ARE ENCOURAGED TO REVIEW THESE TERMS OF USE PERIODICALLY FOR UPDATES AND CHANGES.</p>
                <h4>TERMS AND CONDITIONS</h4>
                <h6>Personal Information</h6>
                <p>You can visit the Website and access most of the content, features and functionality (the “Content”) without being required to provide us with any personal information. However, access to certain content will require that you provide us with some personally identifying information about yourself, as more specifically detailed in our privacy policy, located here.</p>
                <h6>Age Requirements</h6>
                <p>The TeamSeas Website is intended solely for users who are of the required age to act on their own behalf in their jurisdiction/country (“child”) and any registration by, use of or access to the Website by anyone who is a child (under 13 in the United States) is strictly prohibited. If you are a child you must review these Terms of Use with your parent or guardian to make sure that your parent or guardian understands them, agrees to be bound by them and you should only use the Website with their permission and under their supervision. Additionally, if you are a parent or guardian of a child and you give your child permission to use the Website, you hereby agree to the terms set forth in these Terms if Use on behalf of both yourself and your child.</p>
                <p>If you reside in a jurisdiction that would restrict the use of the Website - or any of the functionalities or features offered via the Website - because of age, or restricts the ability to enter into contracts such as this one due to age, you must abide by such age limits and you must not use the Website if you are not permitted to do so by such local jurisdiction.</p>
                <h6>Intellectual property rights</h6>
                <p className="i">Trademarks and Service Marks</p>
                <p>Certain trademarks are the service marks and trademarks of Mr.Beast, the Ocean Conservancy or The Ocean Cleanup North Pacific Foundation. All page headers, custom graphics, and button icons are service marks, trademarks, logos, and/or trade dress of Mr.Beast. All other trademarks, service marks, trade dress, product names, company names or logos, whether registered or not, on the Website are the property of their respective owners. In addition to complying with all applicable laws, you agree that you will not use any such trademarks, service marks, trade dress, or other logos from these Website without the prior written authorization of Mr.Beast or their respective owners.</p>
                <p className="i">Copyright</p>
                <p>Except as otherwise expressly stated, all Content appearing on the Website – including all scripts, videos and similar materials, is the copyrighted work of either Mr.Beast or third-party partners and suppliers, and is protected by U.S. and international copyright laws. The compilation (meaning the collection, arrangement and assembly) of all Content is also the exclusive property of Mr.Beast, and is protected by U.S., and international copyright laws. Except as otherwise expressly stated herein or as expressly permitted, you may not alter, modify, copy, distribute (for compensation or otherwise), transmit, display, perform, reproduce, reuse, post, publish, license, frame, download, store for subsequent use, create derivative works from, transfer, or sell any information or Content obtained from the Website, in whole or in part, including any text, images, audio, and video in any manner, without the prior written authorization of Mr.Beast, or any applicable third-party suppliers or authorized users. The use of Content, including images, by you, or anyone else authorized by you, is prohibited unless specifically permitted by Mr.Beast.</p>
                <h6>Reservation of Rights</h6>
                <p>Mr.Beast reserves the right, in its sole discretion and at any time, to modify, interrupt, limit, suspend or discontinue, temporarily or permanently, the Website, in whole or in part, including, as we deem necessary for purposes of maintenance, upgrades and the like, or to maintain the Website or to comply with applicable law. Mr.Beast shall not be liable to you or to any third party for any such modifications, suspensions or discontinuances of the Website.</p>
                <h6>Payments and Payments Processing; Rules for All Payments</h6>
                <p>You can make an online donation to the TeamSeas initiative. Mr.Beast has engaged the services of a variety of third-party payment service provider(s) to process all donation/payment transactions. Mr.Beast is not affiliated with any of these third-party payment service provider(s), and neither is the agent or employee of the other, and Mr.Beast is not responsible in any way for the actions or performance (or lack thereof) of such third-party payment service provider(s). Accordingly, Mr.Beast expressly disclaims responsibility and liability for all payment processor services, and you hereby agree that Mr.Beast shall not be responsible for any loss or damage of any sort incurred as a result of such services.</p>
                <p>You hereby acknowledge and agree that, for all donations, (1) you will not use an invalid or unauthorized credit or debit card or other payment method; (2) all donations are final and non-refundable. If you have any questions regarding any donation, please contact us by phone at (800) 519-1541 or by email at support@support.teamseas.org.</p>
                <h6>Third-Party Beneficiaries</h6>
                <p>Please note that the Ocean Conservancy and The Ocean Cleanup North Pacific Foundation are the two nonprofit organizations who are the recipients of the donations processed through the Website. As such, you hereby acknowledge and agree that both the Ocean Conservancy and The Ocean Cleanup North Pacific Foundation are third-party beneficiaries of these Terms of Use</p>
                <h6>Additional Acknowledgments.</h6>
                <p>You hereby agree to abide by all applicable local, state, national, and international laws and regulations with respect to your use of TeamSeas Website and all Content. In addition, you also acknowledge and agree that use of the Internet and access to or transmissions or communications with Website is solely at your own risk. While Mr.Beast has endeavored to create a secure and reliable Website, you should understand that the confidentiality of any communication or material transmitted to/from Website over the Internet or other form of global communication network cannot be guaranteed. Accordingly, Mr.Beast is not responsible for the security of any information transmitted to or from the Website.</p>
                <h6>Prohibited Use/Activities</h6>
                <p>In addition to any other restrictions or conditions of use, you hereby acknowledge, and represent and warrant, that your use of the Website, will not be, or alleged to be unlawful, unauthorized, fraudulent or malicious in purpose. In addition, you agree you will not:</p>
                <ol>
                    <li>license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Website or Content or in any way;</li>
                    <li>modify or make derivative works based upon the Website or Content;</li>
                    <li>create Internet “links” to the Service or “frame” or “mirror” the Website on any other server or wireless or Internet-based device;</li>
                    <li>launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Website;</li>
                    <li>interfere with or disrupt the integrity or performance of the Website or the data contained therein, or attempt to gain unauthorized access to the Website or its related systems or networks.</li>
                </ol>
                <p>Mr.Beast will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. You acknowledge that Mr.Beast has no obligation to monitor your access to or use of the Website, but has the right to do so for the purpose of operating the Website and providing the Services, to ensure your compliance with these Terms of Use, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body.</p>
            </div>
        </div>
    )
}